### ISSUE TITLE
Does it support Android?

### ISSUE THREAD

**Issue by KevinHu2014** [FuYaoDe/react-native-app-intro#1]
Does it works on Android?

**Comment by FuYaoDe** [comment]
Sorry...  Not yet support, But I'll add to TODO list

**Comment by LL101SS** [comment]
android上不行

**Comment by BilalBudhani** [comment]
Android support would be a great addition. Looking forward to it. BTW, Plugin works great in iOS. 👍

**Comment by bosung90** [comment]
I just tried it out on Android and it seems like done, next buttons are broken and only shows first page.
Any idea why it is not working on Android properly ?

**Comment by FuYaoDe** [comment]
The main reason for this bug  because it use React Native ViewPagerAndroid achieve ViewPager  not the same with ios, the focus is on  ViewPagerAndroid, in React Native doc say `It is important all children are <View>s and not composite components. `, Can not be used  `<Animated.View>` so... i need find other component Implementation android ViewPager. Almost from the write again....need some time

**Comment by bosung90** [comment]
I was able to get Android working without the parallax effect, at least for now. Thank you for your hard work!

**Comment by redwind** [comment]
on Android, you could fix display Done button bugs by remove View node wrapper Animated.View button.

**Comment by FuYaoDe** [comment]
Hi All, Now 1.1.0 is support Android !!  🎉

**Comment by franzejr** [comment]
Hey @FuYaoDe, I get it working on Android, but it seems the images are not working? I'm using the Basic Usage example which the images are one URL. Any hint? Thanks!

**Comment by FuYaoDe** [comment]
@franzejr  check your simulator network ?
I think next TODO is basic usage support require image.

**Comment by akash-cp** [comment]
Is there anyway to require local images ?
